import Head from "next/head";
import { useRouter } from "next/router";
import { useState, useEffect } from "react";
import Products from "../components/Products/Products";
import Filter from "../components/Filter/Filter";
import styles from "../styles/Home.module.css";
import filter from "../helpers/filters.js";
import pagination from "../helpers/pagination.js";
import InfiniteScroll from "react-infinite-scroll-component";

export async function getServerSideProps() {
  // Fetch data from external API
  const res = await fetch(`http://localhost:3000/api/products`);
  const data = await res.json();
  // Pass data to the page via props
  return { props: { data } };
}

export default function Home(props) {
  const router = useRouter();
  const baseProducts = props.data.result.products;
  const [productItems, setProductItems] = useState(baseProducts);

  const [filterState, setFilterState] = useState({
    sort: "bestsell",
    category: "all",
  });

  useEffect(() => {
    filterHandler(router.query);
    const onRouteChange = (url) => {
      console.log(window.location);
      // filterHandler(router.query);
    };

    if (typeof window !== "undefined") {
      window.addEventListener("popstate", onRouteChange, false);
    }

    return () => {
      if (typeof window !== "undefined") {
        window.removeEventListener("popstate", onRouteChange, false);
      }
    };
  }, []);

  const filterHandler = (val) => {
    setFilterState(val);
    setProductItems(filter(baseProducts, val));
    router.push({ query: val }, undefined, { shallow: true });
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Search Product</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.pageHeadLine}>
        <h1>استیکر فیلم-سریال-انیمیشن</h1>
      </div>
      <Filter onChange={filterHandler} value={filterState} />
      {/* <InfiniteScroll
        dataLength={this.state.items.length}
        next={pagination()}
        hasMore={true}
        loader={<h4>Loading...</h4>}
      > */}
      <Products products={productItems} />
      {/* </InfiniteScroll> */}
    </div>
  );
}
